---
- name: Prepare Bastion Host
  hosts: local
  become: true
  gather_facts: false
  tasks:
    - name: Install build dependencies
      yum:
        name:
          - oracle-epel-release-el8
          - python3-pip
          - git
          - unzip
          - gcc
          - make
          - wget
          - tar
        state: present
        use_backend: dnf

# - name: Download Confluent Offline Install Tarball
#   get_url:
#     url: "https://confluent-tarballs.s3.us-east-1.amazonaws.com/confluent-offline-install-7.7.1-latest.tar.gz"
#     dest: "/home/ec2-user/confluent-offline-install-7.7.1-latest.tar.gz"
#     mode: '0644'
#   retries: 3
#   delay: 5
#   register: download_result
#   until: download_result is succeeded